### ISSUE TITLE
Files nested deeper than ./*/* are not uploaded to S3

### ISSUE THREAD

**Issue by danbohea** [adrianfalleiro/gulp-s3-publish#5]
```
var s3 = require("gulp-s3-publish");

gulp.task('deploy', function () {
  var aws = JSON.parse(fs.readFileSync('./aws.json'));
  gulp.src('./dist/**/*')
    .pipe(s3(aws));
});
```

The task starts and finishes without error but only the first 2 levels of files are uploaded to S3 (./* and ./\*/\*). Any files nested more deeply appear to be skipped.

**Comment by adrianfalleiro** [comment]
@danbohea Do the skipped files not appear at all in the terminal?

Also if you return `gulp.src()` does the issue still occur? If so, could you please provide me with a sample project to help me replicate the issue.

Thanks

**Comment by danbohea** [comment]
Correct, skipped files don't appear in the terminal output.

Just tested with `return gulp.src(...` and it's now working as expected. Amended task looks like this for anyone following along:

```
var s3 = require("gulp-s3-publish");

gulp.task('deploy', function () {
  var aws = JSON.parse(fs.readFileSync('./aws.json'));
  return gulp.src('./dist/**/*')
    .pipe(s3(aws));
});
```

Thanks so much for you help!
